dist: trusty
addons:
  apt:
    sources:
        - travis-ci/sqlite3
    packages:
        - sqlite3
language: node_js
node_js:
    - "12.18.2"
before_install:        
install: 
    - node -v
    - npm -v
    - npm install
    - npm install sqlite3
    - npm install eslint -g      
script: 
    - npm test

