
language: node_js
node_js:
    - "8.6"
before_install:        
install: 
    - node -v
    - npm -v
    - npm install
    - npm install sqlite3
    - npm install eslint -g      
script: 
    - npm start

