
language: node_js
node_js:
    - "8.6"
before_install:        
install: 
    - node -v
    - npm -v
    - npm install
    - npm install sqlite3
    - npm install eslint -g      
script: 
    - npm start
after_script:
    - npm run lint
    - npm run test
    - npm run coverage
    - npm run test:load