openapi: 3.0.0
info:
  title: Rides
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /rides:
    post:
      summary: ''
      operationId: post-rides
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - rideID
                    - startLat
                    - startLong
                    - endLat
                    - endLong
                    - riderName
                    - driverName
                    - driverVehicle
                    - created
                  properties:
                    rideID:
                      type: number
                    startLat:
                      type: number
                    startLong:
                      type: number
                    endLat:
                      type: number
                    endLong:
                      type: number
                    riderName:
                      type: string
                      minLength: 1
                    driverName:
                      type: string
                      minLength: 1
                    driverVehicle:
                      type: string
                      minLength: 1
                    created:
                      type: string
                      minLength: 1
              examples:
                example-1:
                  value:
                    - rideID: 0
                      startLat: 0
                      startLong: 0
                      endLat: 0
                      endLong: 0
                      riderName: string
                      driverName: string
                      driverVehicle: string
                      created: string
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                start_lat:
                  type: number
                  exclusiveMinimum: true
                end_lat:
                  type: number
                start_long:
                  type: number
                end_long:
                  type: number
                rider_name:
                  type: string
                  minLength: 1
                driver_name:
                  type: string
                  minLength: 1
                driver_vehicle:
                  type: string
                  minLength: 1
              required:
                - start_lat
                - end_lat
                - start_long
                - end_long
                - rider_name
                - driver_name
                - driver_vehicle
            examples:
              example-1:
                value: {}
      description: test
components:
  schemas: {}
  securitySchemes: {}
